production:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - python
    - numpy
    - pyunitwizard
    - mmtf-python
    - pandas
    - mdtraj
    - mdanalysis
    - openmm
    - pdbfixer
    - openmmtools
    - biopython
    - nglview
    - parmed
    - pytraj
    - openopenmmreporters
    - openmolecularsystems

development:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - python
    - numpy
    - pyunitwizard
    - mmtf-python
    - pandas
    - mdtraj
    - mdanalysis
    - openmm
    - pdbfixer
    - openmmtools
    - biopython
    - nglview
    - parmed
    - pytraj
    - jupyterlab
    - matplotlib
    - openopenmmreporters
    - openmolecularsystems

test:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - python
    - numpy
    - pyunitwizard
    - mmtf-python
    - pandas
    - mdtraj
    - mdanalysis
    - openmm
    - pdbfixer
    - openmmtools
    - biopython
    - nglview
    - parmed
    - pytraj
    - jupyterlab
    - matplotlib
    - openopenmmreporters
    - openmolecularsystems
    - pytest
    - pip
    - pytest-cov
    - codecov

docs:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - python
    - numpy
    - pyunitwizard
    - mmtf-python
    - pandas
    - mdtraj
    - mdanalysis
    - openmm
    - pdbfixer
    - openmmtools
    - biopython
    - nglview
    - parmed
    - pytraj
    - jupyterlab
    - matplotlib
    - openopenmmreporters
    - openmolecularsystems
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - recommonmark
    - sphinx-markdown-tables

setup:
  channels:
    - defaults
  dependencies:
    - python
    - setuptools
    - numpy
    - versioneer

conda-build:
  channels:
    - uibcdf/label/dev
    - uibcdf
    - conda-forge
    - ambermd
    - defaults
  dependencies:
    - anaconda-client
    - conda-build

