package:
  name: sabueso
  version: 0.0.1

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy

  run:
    - python  {{ python }}
    - numpy
    - jupyterlab
    - pytools_uibcdf
    - chembl_webresource_client
    - gevent-openssl
    - urllib3
    - jsonschema
    - libxml2
    - xmltodict

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    To be written
  dev_url: https://github.com/uibcdf/Sabueso
  doc_url: https://uibcdf.org/Sabueso
