from .get_name import get_name
from .get_key_name import get_key_name
from .get_short_name import get_short_name
from .get_uniprot_entry_name import get_uniprot_entry_name
from .get_alternative_names import get_alternative_names
from .get_organism import get_organism
from .get_function import get_function
from .get_interactions import get_interactions
from .get_subunit_structure import get_subunit_structure
from .get_ec import get_ec
from .get_organism_common_name import get_organism_common_name
from .get_organism_scientific_name import get_organism_scientific_name
from .get_uniprot import get_uniprot
from .to_string_uniprot import to_string_uniprot
from .get_dbreference import get_dbreference
from .get_pdbs import get_pdbs
from .get_host import get_host
from .get_canonical_sequence import get_canonical_sequence
from .get_isoforms import get_isoforms
from .get_chains import get_chains
from .get_domains import get_domains
from .get_regions import get_regions
from .get_protein_card import get_protein_card

