package:
  name: sabueso
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - setuptools
  - numpy
  run:
  - python
  - setuptools
  - numpy
  - evidence
  - pyunitwizard
  - mmtf-python
  - pandas
  - xmltodict
  - chembl_webresource_client
about:
  home: https://uibcdf.org
  license: MIT License
  summary: ''
  description: 'To be written

    '
  dev_url: https://github.com/uibcdf/Sabueso
  doc_url: https://uibcdf.org/Sabueso
